### ISSUE TITLE
locale missing from wheelroom-config.d.ts when getting started

### ISSUE THREAD

**Issue by thebiglabasky** [wheelroom/wheelroom#106]
Hi team!

I've been giving a shot at the getting started guide but faced a compilation exception in `src/config/wheelroom-config.d.ts` when running `npm run compile-config` at [this step](https://github.com/wheelroom/wheelroom/blob/master/packages/boilerplate/docs/getting-started.md#compile-wheelroom-config).

Here's the output:
```
> @wheelroom/boilerplate@3.3.1 compile-config /Users/hervelabas/Dev/wheelroom/testwheelroom
> tsc --project src/config/tsconfig.json

src/config/wheelroom-config.ts:7:14 - error TS2741: Property 'locale' is missing in type '{ commonFields: WheelroomFields; components: WheelroomComponents; fieldDefaults: FieldDefaults; plugins: ({ options: { contentSets: { ...; }; fieldDefinitions: ContentfulFieldDefinitions; replaceSets: ReplaceSets; templateSets?: undefined; }; resolve: string; } | { ...; })[]; }' but required in type 'WheelroomConfig'.

7 export const config: WheelroomConfig = {
               ~~~~~~

  node_modules/@wheelroom/wheelroom/dist/types/wheelroom-config.d.ts:14:5
    14     locale: string;
           ~~~~~~
    'locale' is declared here.


Found 1 error.
```

Adding `locale: 'en-US'` (or whatever locale is in the space) makes it work.

I'd suggest putting this as a default.

I'm using Node v14.3.0 on MacOS Catalina 10.15.4 if that's of any use.

--
EDIT: added environment details

**Comment by jaccomeijer** [comment]
Thanks for getting back to us! We started a small refactor last monday in the refactor/pageSection branch as described in #105. That refactor took a little longer than the 1 day we expected ;-)

This bug is fixed in the refactor branch. That branch became a major cleanup which will greatly improve how to update to a new version. We hope to merge this within a couple of days!
