### ISSUE TITLE
How to handle LARGE variations of variations like card and cardShadow (refactor/themes branch)

### ISSUE THREAD

**Issue by jaccomeijer** [wheelroom/wheelroom#114]
### Proposal: topicInfo/shadowCards

- Create a new variant for these trees
- Like topicSection/cards and topicSection/shadowCards
- Deep merge objects in theme to avoid duplicate styles

**Comment by thijskrooswijk** [comment]
Deep merge object(s) in your theme is the best approach for section variations. You can merge parts or the whole Style-Tree. It is very flexible and easy to maintain.

**Comment by jaccomeijer** [comment]
Agreed!
