### ISSUE TITLE
How to handle SMALL ncss variations? (refactor/themes branch)

### ISSUE THREAD

**Issue by jaccomeijer** [wheelroom/wheelroom#115]
### Proposal: ncss-header

- The ncss-header solution is not a good idea because it is hard to check with
  Typescript

### Proposal: Array of ncss objects

- besides ncss: {}, allow ncss: [{}, {}, ...]
- this is easy to check with TS and not verbose
- problem is that the ncss objects in the array do not have a name
- add wrName to ncss object?

```ts
export const styleTreeA = {
  container: {
    ncss: {
      label: 'container',
      p: 1,
    },
  },
  topic: {
    ncss: [
      {
        label: 'topic-blue',
        p: 1,
        color: 'blue',
      },
      {
        label: 'topic-red',
        p: 1,
        color: 'red',
      },
    ],
    content: {
      ncss: {
        label: 'topic-content',
        p: 1,
      },
    },
  },
}
```
### Proposal: ncssGroup

- besides ncss: {}, allow ncssGroup
- this is easy to check with TS and not verbose
- solves problem of array, objects have a name
- does exactly what we need, group ncss variations

```ts
export const styleTreeB = {
  container: {
    ncss: {
      label: 'container',
      p: 1,
    },
  },
  topic: {
    ncssGroup: {
      blue: {
        label: 'topic',
        p: 1,
        color: 'blue',
      },
      red: {
        label: 'topic',
        p: 1,
        color: 'red',
      },
    },
    content: {
      ncss: {
        label: 'topic-content',
        p: 1,
      },
    },
  },
}
```

**Comment by thijskrooswijk** [comment]
@jaccomeijer The second proposal looks more solid and easier to read. I would only change `ncssGroup: {}` into `ncssVariations: {}`. The word Variations explains better what a developer is expecting.

**Comment by jaccomeijer** [comment]
As discussed, we'll use:
```js
const ncssSwitch = {
  blueVariation: {
  },
  redVariation: {
  },
}
