### ISSUE TITLE
Write a solid plan for styling overrides

### ISSUE THREAD

**Issue by jaccomeijer** [wheelroom/wheelroom#25]
When display variants move to npm modules we need a uniform way of how we apply styles. So that it's clear how modifying commonStyles affect display variants from npm modules.

**Comment by jaccomeijer** [comment]
Ref #22

**Comment by thijskrooswijk** [comment]
@jaccomeijer we have to remove all overrides. As a developer you have to use the ncss props as an override.

**Comment by jaccomeijer** [comment]
Using styleTrees solves this
