### ISSUE TITLE
Video doesn't show on iOS

### ISSUE THREAD

**Issue by jaccomeijer** [wheelroom/wheelroom#55]
Open on a real iOS device: https://boilerplate.wheelroom.io/examples

Video's don't show a background image, just a grey play button. There's no way of getting the video to play.

**Comment by thijskrooswijk** [comment]
@jaccomeijer we need to add a Poster image like this:
```
<video controls playsinline poster="poster-image.png">
    <source src="video.mp4" type="video/mp4">
</video> 
```

**Comment by jaccomeijer** [comment]
HTML5 provides the `<video>` media element for working with videos. Inside the `<video>` element, you can provide multiple `<source>` elements that serve as different file formats the video player can use, with each browser electing to use a format it supports.

De meest simpele oplossing qua datamodel in Contentful is om van media een lijst met media te maken. Je kunt dan verschillende resoluties van de video uploaden en ook een cover image. In js kun je eenvoudig detecteren of het een lijst met video's is en of er een cover image is.

**Comment by thijskrooswijk** [comment]
@jaccomeijer adding an extra topic as a video poster (image) will be preferable. But does Contentful not provide a video poster? Pretty weird because they use video in their Headless CMS, right?

**Comment by thijskrooswijk** [comment]
@jaccomeijer maybe we can use this plugin or parts of it? https://github.com/cupojoe/gatsby-remark-video-poster

**Comment by jaccomeijer** [comment]
This appears to be the video size. On iPhone X no video's, while on iPhone 11 the video's show. More video sizes and a poster are needed.

Real question therefore is, how to do this in Contentful?

**Comment by thijskrooswijk** [comment]
done! https://github.com/wheelroom/wheelroom/commit/c8a5e2f92fa84c383a0e9d68902858e92ebe784f

**Comment by jaccomeijer** [comment]
I reopen this because I would like to test this on a real iOS device.

@thijskrooswijk What url did you use to test this? The url above I used to reproduce this issue does not work anymore.

**Comment by jaccomeijer** [comment]
The video's I see in the boilerplate don't work on my phone.

We need something like browserstack to fix this I think. I've added video's on different resolutions to wheelroom-io media.

<img width="622" alt="screen" src="https://user-images.githubusercontent.com/32537642/82790463-623c5880-9e6c-11ea-93f3-c97422a7bb3e.png">

**Comment by jaccomeijer** [comment]
Problem solved. That is, we identified why it the video did not start.

The problem was solved by turning this switch on:
iOS setting -> Safari -> Advanced -> Experimental features -> Pointer events

**Comment by thijskrooswijk** [comment]
![F09B83B7-B0A3-4535-AA4D-C2FD88066245](https://user-images.githubusercontent.com/2682696/82837619-deb15480-9ec9-11ea-93e4-45bda62008ff.jpeg)
