### ISSUE TITLE
Create new content set

### ISSUE THREAD

**Issue by jaccomeijer** [wheelroom/wheelroom#57]
Now that we use topics, create a new content set which creates a couple of pages and navigation. Add page sections for all default displays.

**Comment by jaccomeijer** [comment]
Start is here. A set has been created that creates one page with some content.

Need to replace this with interesting demo content.

**Comment by thijskrooswijk** [comment]
Wheelroom Boilerplate have now two content-sets:
- starterSet
- exampleSet

https://github.com/wheelroom/wheelroom/commit/584b92b418dc57af8918f97cba7647c195170f81
