### ISSUE TITLE
Video embeds

### ISSUE THREAD

**Issue by jaccomeijer** [wheelroom/wheelroom#63]
Allow youtube video's to be embedded

**Comment by thijskrooswijk** [comment]
Done! https://github.com/wheelroom/wheelroom/commit/9d2ed584f29cb30a981fa98135474f0baa347a85

**Comment by thijskrooswijk** [comment]
And done! https://github.com/wheelroom/wheelroom/commit/a79c954a5ed1e09f2a69cd15b5f0780a1679bd62
