### ISSUE TITLE
Change the License to MPL or LGPL

### ISSUE THREAD

**Issue by thijskrooswijk** [wheelroom/wheelroom#67]
My preference is MPL 2.0. You need to commit all your code changes to the project, but as they say, you can get away by that. @jaccomeijer – what do you think?

**Pros and cons**
- https://softwareengineering.stackexchange.com/questions/221365/mozilla-public-license-mpl-2-0-vs-lesser-gnu-general-public-license-lgpl-3-0

**List of licenses**
- https://help.github.com/en/github/creating-cloning-and-archiving-repositories/licensing-a-repository

**Comment by jaccomeijer** [comment]
@thijskrooswijk The license does not need to be waterproof, it should reflect our intentions. We would like the community to contribute. I think we need a license that encourages that. I feel that forcing contributions is not the way to achieve contribution.

**Comment by thijskrooswijk** [comment]
A decision is been made. Wheelroom will have an MIT license.
