### ISSUE TITLE
Add "lerna clean" in bootstrap-packages.sh

### ISSUE THREAD

**Issue by thijskrooswijk** [wheelroom/wheelroom#72]

**Comment by jaccomeijer** [comment]
The bootstrap process might be quick on a fast machine. On slower machines like a regular MacBook Air the process takes up quite some time when running from scratch. Luckily not all modules have to be reinstalled on a re-run. Adding `lerna clean` would make the run always real slow on slow machines. It's better to know what you are doing and do the `lerna clean` youself ;-)

**Comment by thijskrooswijk** [comment]
@jaccomeijer – I agree, but is this documented in our Docs?

**Comment by jaccomeijer** [comment]
The script has a description with this line:
```
# Note: you might want to run 'lerna clean' before using the script
```

For now there's the Lerna docs and common sense.

- First we need an audience for proper docs on the build process
- Then we need to write the docs
- Lastly we possibly need a 'solving common problems' section ;-)
