### ISSUE TITLE
Adding FontSize on Blockquote element results in exact value(s) and not from Styled-system

### ISSUE THREAD

**Issue by thijskrooswijk** [wheelroom/wheelroom#73]
@jaccomeijer check the file `elements-styles.ts` row `17`.
Applying fontSize results in '6' and not the expected Styled-system scales.
The styles should have an effect on the page-section blockquote variation.
I think that the parser or the deepMerge is causing the problem.

**Comment by jaccomeijer** [comment]
See: [section-quote-style.ts](https://github.com/wheelroom/wheelroom/tree/master/packages/boilerplate/src/themes/yosemite/sections/section-quote-style.ts#L26)
